### ISSUE TITLE
Product Card

### ISSUE THREAD

**Issue by mirsahib** [mirsahib/GroceWise#8]
Create a product card with the following item:
- image 
- title 
- price (input field)
- description
- shelf life (input field)
- Add button

**Comment by danicunhac** [comment]
@mirsahib could you assign me this issue?

**Comment by juancmandev** [comment]
What means "editable field"? The card is not a read-only component? Those fields should be inputs?

**Comment by mirsahib** [comment]
Yes input field

**Comment by juancmandev** [comment]
<img width="393" alt="Screenshot 2023-08-11 at 12 02 25 p m" src="https://github.com/mirsahib/GroceWise/assets/59628111/6a68eb76-c02e-4e4a-aed8-a5b4348802c9">
